import './globals.css';
import Link from 'next/link';
import Image from 'next/image'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
    <html lang='en'>
      <body>
        <nav className='navbar
        '>
        <Link href='/'>Home </Link>
       |
        <Link href='/about'> About</Link>
        </nav>
        <Image id='img'src={"/hello-kitty.png"} alt={"hi"} width={50} height={50}/>
        {children}
        </body>
    </html></>
  );
}
